// <auto-generated />
using Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Backend.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180103020548_AtualizacaoGeral")]
    partial class AtualizacaoGeral
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Backend.Database.Models.Colaborador", b =>
                {
                    b.Property<int>("EmpresaId");

                    b.Property<int>("PessoaId");

                    b.Property<string>("Cargo");

                    b.Property<DateTime>("DtCadastro");

                    b.Property<DateTime?>("DtDemissao");

                    b.Property<decimal>("Salario");

                    b.Property<int>("Status");

                    b.HasKey("EmpresaId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Backend.Database.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cnpj");

                    b.Property<DateTime>("DtCadastro");

                    b.Property<string>("Nome");

                    b.Property<string>("RazaoSocial");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Backend.Database.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("DtCadastro");

                    b.Property<DateTime>("DtNascimento");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Backend.Database.Models.Colaborador", b =>
                {
                    b.HasOne("Backend.Database.Models.Empresa", "Empresa")
                        .WithMany("Colaboradores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Database.Models.Pessoa", "Pessoa")
                        .WithMany("Colaboradores")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
